<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // ── media_assets ───────────────────────────────────────────────────
        Schema::create('media_assets', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('owner_user_id')->nullable();
            $table->unsignedBigInteger('channel_id')->nullable();
            $table->enum('type', ['image', 'video', 'audio', 'document', 'thumbnail']);
            $table->enum('storage_provider', [
                'local', 's3', 'cloudinary',
                'youtube', 'vimeo', 'facebook', 'instagram', 'tiktok'
            ])->default('s3');
            $table->string('disk', 20)->default('s3');
            $table->string('original_url', 500)->nullable();
            $table->string('internal_path', 500)->nullable(); // S3 key or local path
            $table->string('external_id', 200)->nullable();   // YouTube video ID etc.
            $table->string('title', 255)->nullable();
            $table->text('description')->nullable();
            $table->string('alt_text', 320)->nullable();       // Accessibility — required on images
            $table->string('mime_type', 100)->nullable();
            $table->unsignedBigInteger('size_bytes')->nullable();
            $table->unsignedSmallInteger('width')->nullable();
            $table->unsignedSmallInteger('height')->nullable();
            $table->unsignedInteger('duration_seconds')->nullable();
            $table->timestamp('uploaded_at')->useCurrent();
            $table->softDeletes();
            $table->timestamps();

            $table->index(['type', 'storage_provider']);
            $table->index('owner_user_id');
            $table->index('channel_id');

            $table->foreign('owner_user_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('channel_id')->references('id')->on('channels')->nullOnDelete();
        });

        // ── media_asset_variants ───────────────────────────────────────────
        // Auto-generated by Spatie Media Library: thumb(300w), medium(800w), large(1600w), webp versions
        Schema::create('media_asset_variants', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('media_asset_id');
            $table->string('conversion_name', 80); // thumb | medium | large | webp_large
            $table->string('disk', 20)->default('s3');
            $table->string('path', 500);
            $table->string('mime_type', 100)->nullable();
            $table->unsignedBigInteger('size_bytes')->nullable();
            $table->unsignedSmallInteger('width')->nullable();
            $table->unsignedSmallInteger('height')->nullable();
            $table->timestamps();

            $table->index('media_asset_id');
            $table->unique(['media_asset_id', 'conversion_name']);

            $table->foreign('media_asset_id')->references('id')->on('media_assets')->cascadeOnDelete();
        });

        // ── content_media_map ──────────────────────────────────────────────
        // Polymorphic: links media to articles, events, ads, user profiles, etc.
        Schema::create('content_media_map', function (Blueprint $table) {
            $table->id();
            $table->string('content_type', 60); // article | event | advertisement | user_profile | membership_card
            $table->unsignedBigInteger('content_id');
            $table->unsignedBigInteger('media_asset_id');
            $table->enum('purpose', ['featured', 'gallery', 'attachment', 'thumbnail'])->default('gallery');
            $table->unsignedSmallInteger('position')->default(0);
            $table->timestamps();

            $table->index(['content_type', 'content_id']);
            $table->index('media_asset_id');

            $table->foreign('media_asset_id')->references('id')->on('media_assets')->cascadeOnDelete();
        });

        // Now we can add the avatar FK on users
        Schema::table('users', function (Blueprint $table) {
            $table->foreign('avatar_media_id')->references('id')->on('media_assets')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropForeign(['avatar_media_id']);
        });
        Schema::dropIfExists('content_media_map');
        Schema::dropIfExists('media_asset_variants');
        Schema::dropIfExists('media_assets');
    }
};
